"""
Hermes Agent Scheduled Tasks Export Integration V1.

Inspired by Hermes Agent Cron scheduler architecture: Implements multi-platform
export configurations for scheduled operational tasks, generating portable manifests
(JSON schema, standard crontab, systemd timer, and Kubernetes CronJob specs) without
requiring destructive local cron modifications.
"""

import json
import logging
import re
import time
import uuid
from dataclasses import asdict, dataclass, field
from enum import Enum
from typing import Any, Callable, Dict, List, Optional, Set, Tuple, Union

logger = logging.getLogger(__name__)


class ExportFormat(str, Enum):
    JSON = "json"
    CRONTAB = "crontab"
    SYSTEMD_TIMER = "systemd_timer"
    KUBERNETES_CRONJOB = "kubernetes_cronjob"


@dataclass
class ScheduledTaskDefinition:
    """Represents a portable scheduled task specification."""

    task_id: str
    name: str
    schedule: str  # Cron expression e.g. "0 3 * * *"
    command: str
    args: List[str] = field(default_factory=list)
    env: Dict[str, str] = field(default_factory=dict)
    timeout_seconds: int = 300
    enabled: bool = True
    description: str = ""
    tags: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ScheduledTaskDefinition":
        t_id = str(data.get("task_id") or data.get("id") or f"task_{uuid.uuid4().hex[:8]}")
        return cls(
            task_id=t_id,
            name=str(data.get("name") or t_id),
            schedule=str(data.get("schedule") or data.get("cron") or "0 0 * * *"),
            command=str(data.get("command") or ""),
            args=[str(a) for a in (data.get("args") or [])],
            env={str(k): str(v) for k, v in (data.get("env") or {}).items()},
            timeout_seconds=int(data.get("timeout_seconds", 300)),
            enabled=bool(data.get("enabled", True)),
            description=str(data.get("description") or ""),
            tags=list(data.get("tags") or []),
            metadata=dict(data.get("metadata") or {}),
        )


class HermesCronTasksExporterV1:
    """
    Hermes Scheduled Tasks Exporter V1.

    Exports scheduled agent maintenance and episodic backup tasks into standardized formats.
    """

    CRON_PATTERN = re.compile(r"^(\*|[0-5]?\d)\s+(\*|[01]?\d|2[0-3])\s+(\*|[012]?\d|3[01])\s+(\*|[01]?\d)\s+(\*|[0-7])$")

    def __init__(self, platform_name: str = "magda-agent-ops"):
        self.platform_name = platform_name
        self._tasks: Dict[str, ScheduledTaskDefinition] = {}

    def register_task(
        self,
        task: Union[ScheduledTaskDefinition, Dict[str, Any]],
    ) -> ScheduledTaskDefinition:
        """Register a task definition for export."""
        if isinstance(task, dict):
            task_obj = ScheduledTaskDefinition.from_dict(task)
        else:
            task_obj = task
        self._tasks[task_obj.task_id] = task_obj
        return task_obj

    def get_task(self, task_id: str) -> Optional[ScheduledTaskDefinition]:
        """Fetch task by ID."""
        return self._tasks.get(task_id)

    def list_tasks(self) -> List[ScheduledTaskDefinition]:
        """List all registered tasks."""
        return list(self._tasks.values())

    def export_to_json_manifest(self, indent: int = 2) -> str:
        """Export all tasks as a validated JSON manifest."""
        manifest = {
            "$schema": "https://magda-agent.internal/schemas/scheduled-tasks-v1.json",
            "platform": self.platform_name,
            "version": "1.0.0",
            "generated_at": time.time(),
            "total_tasks": len(self._tasks),
            "tasks": [t.to_dict() for t in self._tasks.values()],
        }
        return json.dumps(manifest, indent=indent)

    def export_to_crontab(self) -> str:
        """Export tasks formatted as standard UNIX crontab lines."""
        lines = [
            f"# Generated by Hermes Scheduled Tasks Exporter ({self.platform_name})",
            f"# Timestamp: {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}",
            "",
        ]
        for task in self._tasks.values():
            if not task.enabled:
                lines.append(f"# DISABLED: {task.name}")
                continue

            cmd_str = task.command
            if task.args:
                cmd_str += " " + " ".join(task.args)

            env_prefix = " ".join(f"{k}={v}" for k, v in task.env.items())
            if env_prefix:
                full_cmd = f"{env_prefix} {cmd_str}"
            else:
                full_cmd = cmd_str

            lines.append(f"# {task.name}: {task.description}")
            lines.append(f"{task.schedule} {full_cmd}")
            lines.append("")

        return "\n".join(lines)

    def export_to_systemd_timer(self, task_id: str) -> Tuple[str, str]:
        """
        Generate systemd .service and .timer configurations for a task.
        Returns: (service_unit_content, timer_unit_content)
        """
        task = self.get_task(task_id)
        if not task:
            raise ValueError(f"Task '{task_id}' not found.")

        cmd_str = task.command
        if task.args:
            cmd_str += " " + " ".join(task.args)

        env_lines = "\n".join(f"Environment=\"{k}={v}\"" for k, v in task.env.items())

        service_content = f"""[Unit]
Description={task.name} - {task.description}
After=network.target

[Service]
Type=oneshot
{env_lines}
ExecStart={cmd_str}
TimeoutSec={task.timeout_seconds}

[Install]
WantedBy=multi-user.target
"""

        # Convert simple daily cron to OnCalendar
        on_calendar = "daily"
        if task.schedule == "0 3 * * *":
            on_calendar = "*-*-* 03:00:00"
        elif task.schedule == "0 0 * * *":
            on_calendar = "*-*-* 00:00:00"

        timer_content = f"""[Unit]
Description=Timer for {task.name}
Requires={task.task_id}.service

[Timer]
OnCalendar={on_calendar}
Persistent=true

[Install]
WantedBy=timers.target
"""
        return service_content.strip(), timer_content.strip()

    def export_to_kubernetes_cronjob(
        self,
        task_id: str,
        image: str = "magda-agent:latest",
        namespace: str = "default",
    ) -> Dict[str, Any]:
        """
        Generate a Kubernetes batch/v1 CronJob manifest for a task.
        """
        task = self.get_task(task_id)
        if not task:
            raise ValueError(f"Task '{task_id}' not found.")

        env_list = [{"name": k, "value": str(v)} for k, v in task.env.items()]

        return {
            "apiVersion": "batch/v1",
            "kind": "CronJob",
            "metadata": {
                "name": task.task_id.replace("_", "-").lower(),
                "namespace": namespace,
                "labels": {
                    "app.kubernetes.io/managed-by": "hermes-cron-exporter",
                    "app.kubernetes.io/name": task.name.replace(" ", "-").lower(),
                },
            },
            "spec": {
                "schedule": task.schedule,
                "concurrencyPolicy": "Forbid",
                "successfulJobsHistoryLimit": 3,
                "failedJobsHistoryLimit": 1,
                "jobTemplate": {
                    "spec": {
                        "activeDeadlineSeconds": task.timeout_seconds,
                        "template": {
                            "spec": {
                                "restartPolicy": "OnFailure",
                                "containers": [
                                    {
                                        "name": task.task_id.replace("_", "-").lower(),
                                        "image": image,
                                        "command": [task.command],
                                        "args": task.args,
                                        "env": env_list,
                                    }
                                ],
                            }
                        },
                    }
                },
            },
        }

    def validate_manifest(self, manifest_data: Union[Dict[str, Any], str]) -> Tuple[bool, List[str]]:
        """Validate an exported manifest against structural constraints."""
        errors = []
        if isinstance(manifest_data, str):
            try:
                data = json.loads(manifest_data)
            except Exception as e:
                return False, [f"Invalid JSON: {e}"]
        else:
            data = manifest_data

        if not isinstance(data, dict):
            return False, ["Manifest must be a JSON object."]

        if "tasks" not in data or not isinstance(data["tasks"], list):
            errors.append("Manifest missing 'tasks' array.")
        else:
            for idx, t in enumerate(data["tasks"]):
                if not t.get("task_id"):
                    errors.append(f"Task at index {idx} missing 'task_id'.")
                if not t.get("command"):
                    errors.append(f"Task at index {idx} missing 'command'.")
                if not t.get("schedule"):
                    errors.append(f"Task at index {idx} missing 'schedule'.")

        return len(errors) == 0, errors
